pipeline {
    agent any
    tools {
        maven 'Maven 3'   // name you configured in Jenkins tools
        jdk 'JDK21'       // if configured under JDK installations
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
